name: Build i915 for DSM Platforms

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    tags:
      - "*-dsm-*"

jobs:
  build:
    strategy:
      matrix:
        version: [7.2]
        platform: [epyc7002, geminilakenk] #, r1000nk, v1000nk]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download toolchain
        run: |
          env_tarball=ds.${{ matrix.platform }}-${{ matrix.version }}.env.txz
          wget -q https://global.synologydownload.com/download/ToolChain/toolkit/${{ matrix.version }}/${{ matrix.platform }}/$env_tarball
          mkdir toolchain
          tar xf $env_tarball -C toolchain

      - name: Download kernel source
        run: |
          dev_tarball=ds.${{ matrix.platform }}-${{ matrix.version }}.dev.txz
          wget -q https://global.synologydownload.com/download/ToolChain/toolkit/${{ matrix.version }}/${{ matrix.platform }}/$dev_tarball
          mkdir ksrc
          tar xf $dev_tarball -C ksrc

      - name: Build
        run: |
          export BACKPORT_DIR=$PWD
          export KLIB_BUILD=$PWD/ksrc/usr/local/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/sys-root/usr/lib/modules/DSM-${{ matrix.version }}/build
          export CROSS_COMPILE=$PWD/toolchain/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-
          ls -l $KLIB_BUIL
          make defconfig-drm
          make -j$(nproc) modules_copy

      - name: Pack modules
        working-directory: out
        run: zip -r i915_dsm-${{ matrix.version }}_${{ matrix.platform }}.zip modules

      - name: Save to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: i915_dsm-${{ matrix.version }}_${{ matrix.platform }}
          path: out/i915_dsm-${{ matrix.version }}_${{ matrix.platform }}.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Append tag to filename
        working-directory: artifacts
        run: |
          find . -name "i915_dsm-*.zip" -print0 | while read -d $'\0' f; do
            mv $f ${f%.*}_${GITHUB_REF##*/}.zip
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: versions
          files: artifacts/**/i915_dsm-*.zip
