name: Extract i915 firmware for DSM

on:
  workflow_dispatch:
  push:
    tags:
      - "*-dsm-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout firmware
        uses: actions/checkout@v4
        with:
          repository: intel-gpu/intel-gpu-firmware
          path: intel-gpu-firmware

      - name: Copy necessary firmware
        run: |
          SOURCE=intel-gpu-firmware/firmware
          DEST=out/firmware
          mkdir -p $DEST
          while read L; do
            L=$(basename $L)
            if [ -e "$SOURCE/$L" ]; then
              cp "$SOURCE/$L" $DEST
            else
              echo "::warning ::Missing $L"
            fi
          done < <(find out/modules -name \*.ko -exec /sbin/modinfo {} -F firmware \;)
          chmod 644 $DEST/*

      - name: Pack modules and firmware
        working-directory: out
        run: zip -r i915_dsm_firmware.zip firmware

      - name: Save to artifacts
        uses: actions/upload-artifact@v4
        with:
          path: out/i915_dsm_firmware.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Append tag to filename
        working-directory: artifacts
        run: |
          find . -name "i915_dsm_*.zip" -print0 | while read -d $'\0' f; do
            mv $f ${f%.*}_${GITHUB_REF##*/}.zip
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: versions
          files: artifacts/**/i915_dsm_*.zip
